feat : added encodeExperiment into jsDOE as per issue #7
cheminfo/jsDOE pull request #8
Opened 2022-01-28 17:19 UTC by aiday-mar

2022-01-31 07:43 UTC, kjappelbaum commented
Hi!

@lpatiny should `xSampling` not be moved to somewhere in mljs? Alt least in `spectra-processing`?

2022-01-31 08:04 UTC, kjappelbaum commented
Perhaps it is even easier if you follow the builder pattern, e.g. https://github.com/tirthajyoti/doepy/tree/master/doepy. 

Then, for some designs, you will only take min and max whereas for others you will consider the full array. 

Only the generalized subset design will work will with the full list of factors as input.

2022-02-01 13:44 UTC, lpatiny requested changes

2022-02-01 13:44 UTC, lpatiny commented on src/encodeExperiment.js
> +    if ('min' in array[i]) {
If we now the property name we would rather use

array[i].min!==undefined

2022-02-01 13:44 UTC, lpatiny commented on src/encodeExperiment.js
> +      let min = array[i]['min'];
```suggestion
      let min = array[i].min;
```

2022-02-01 13:44 UTC, lpatiny commented on src/encodeExperiment.js
> +      let sampling = array[i]['sampling'];
```suggestion
      let sampling = array[i].sampling;
```

Same should be done everywhere

2022-02-01 13:44 UTC, lpatiny commented on src/encodeExperiment.js
> +  return { returnArray, decodeExperiment };
We could rename the variable:
- returnArray => experiments

2022-05-19 09:42 UTC, kjappelbaum approved these changes

2022-05-19 09:42 UTC, merged